version: '3.8'

services:
  todo-front:
    image: todo-ca-front
    container_name: todo-ca-front
    build:
      context: .
      dockerfile: container/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5173:5173'
